### PR TITLE
Ft homepage 161609025

### PR DESCRIPTION
**Pull request by kelvinndmo**
### what does this PR do?

 - creates a home page

## Tasks completed:
 -  welcome user to the page
 -  User can place a parcel order without necessarily signing up or login.
 - User will however be forced to sign up once he/she is sure of placing a parcel order
 
### clone the repo as below:

git clone -b ft-homepage-161609025 git@github.com:kelvinndmo/send.git

## cd UI/pages
open users.html in your browser

## What are the relevant pivotal tracker stories?
 #161609025
### Screenshots
n1
n2

### CODE REVIEW

**Comment by Bakley** [comment]
Wow, I really like your work. This is amazing

**Comment by ChegeBryan** [comment]
That color combination is cool 👌 simplicity is key.

**Comment by SimonAwiti** [comment]
The UI look nice....about log in? both the admin and regular user logs in at the same point?...then how do you differentiate the two?
otherwise it looks awesome

**Comment by MamboBryan** [comment]
This is an amazing page. Wow just wow.

**Comment by MuthomiGuantai** [comment]
UI looks really nice..good work

**Comment by Kibetchirchir** [comment]
Nice work

**Comment by BrianSerem** [comment]
cool blend with the colors

**Pull request merged**
